# Generated by Django 4.1.7 on 2023-03-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="adventureplaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("state", models.CharField(default="Windsor", max_length=50)),
                ("country", models.CharField(default="Canada", max_length=50)),
            ],
        ),
    ]
