# Generated by Django 4.1.7 on 2023-03-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_bookings_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="booking_for_the_date",
            field=models.DateField(null=True),
        ),
    ]
