# Generated by Django 4.1.7 on 2023-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_bookings_booking_for_the_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="view",
            field=models.CharField(
                choices=[("Day view", "Day view"), ("Night view", "Night view")],
                max_length=10,
            ),
        ),
    ]
