# Generated by Django 4.1.7 on 2023-03-17 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_bookings_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventureplaces",
            name="picture",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="../static/uploads"
            ),
            preserve_default=False,
        ),
    ]
