# Generated by Django 4.1.7 on 2023-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_adventureplaces_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventureplaces",
            name="picture",
            field=models.ImageField(
                default="/Users/harika/PycharmProjects/pythonProject/djangoProject/Hotairballonbooking/app/static/uploads/Screen Shot 2023-03-09 at 4.33.56 PM.png",
                upload_to="../static/uploads",
            ),
        ),
    ]
