# Generated by Django 4.1.7 on 2023-03-17 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_adventureplaces_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventureplaces",
            name="Description",
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adventureplaces",
            name="picture",
            field=models.ImageField(
                default="/Users/harika/PycharmProjects/pythonProject/djangoProject/Hotairballonbooking/app/static/uploads/Default.jpeg",
                upload_to="../static/uploads/",
            ),
        ),
    ]
