# Generated by Django 4.1.7 on 2023-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_adventureplaces_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventureplaces",
            name="picture",
            field=models.ImageField(
                default="/Users/harika/PycharmProjects/pythonProject/djangoProject/Hotairballonbooking/app/static/uploads/Default.jpeg",
                upload_to="uploads/",
            ),
        ),
    ]
